version: '3'
services:
  client:
    container_name: client
    build:
      context: .
    volumes:
      - clientvol:/clientdata
    networks:
      - backend
      - proxy

networks:
  backend: {}
  proxy:
    name: proxy_network

volumes:
  clientvol:
    name: clientvol
