version: '3'
services:
  client:
    container_name: client
    build:
      context: .
    ports:
      - 8080:5000
    volumes:
      - clientvol:/clientdata
    networks:
      - backend

networks:
  backend: {}

volumes:
  clientvol: {}
