version: '3'
services:
  client:
    container_name: client
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - clientvol:/clientdata
    environment:
      - SERVER_IP=${SERVER_IP}
    networks:
      - backend

networks:
  backend: {}

volumes:
  clientvol: {}
