name: Capstone-client (Build test and deploy client application)

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  job1_build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: umerarshad123/capstone_client:latest

  job2_deploy_image:
    runs-on: self-hosted
    needs: job1_build_push_image
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      -
        name: Pull and run updated docker image
        run: |
          cd /home/ec2-user/DiceCapstonePart1Client
          pwd
          echo "IMAGE_TAG=${{ secrets.docker_username }}/capstone_client:${{ env.TAG }}" > .env
          docker-compose up -d

